### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by filipovw** [Purfview/whisper-standalone-win#143]
You've done great work with this app! I am using the linux version, but I have 2 questions: why can't we see the source code in the repository and why do you recommend to run as an administrator/sudo? I would love it if I could see how it is built, as I want to use this for a project in the making. Maybe the discussions are a better place to post this. Thanks.

**Comment by Purfview** [comment]
> You've done great work with this app! I am using the linux version...

Thanks. Keep that ~4% alive!

> why do you recommend to run as an administrator/sudo?

It's double foolproof recommendation, as some newbies don't listen to the advice not to copy it to the Windows folders, maybe they will listen to run it as admin then. Looks like it works as I don't get those silly issues posted anymore. 😆

> why can't we see the source code in the repository

Model code is there -> https://github.com/SYSTRAN/faster-whisper
CLI code is not here because I don't want to maintain it on GitHub [call me lazy] and I don't want newbies having the wrong ideas that it's something installable in Python.
Maybe I would keep it on GitHub if there was non-close-to-zero chance somebody contributing anything to it. 😝

>  I would love it if I could see how it is built, as I want to use this for a project in the making.

Someone asked me this before, you can find links, anyway those are dated now.
Most of it's just copy/paste from the vanilla Whisper repo. Btw, you and others should know that it's easily extractable from the exe, probably it would be as the first answer in Google how to do it.

Anyway, I pasted the current cli there -> https://pastebin.com/SUGMHqQH
