### ISSUE TITLE
Remove the advertisements

### ISSUE THREAD

**Issue by Purfview** [Purfview/whisper-standalone-win#365]
## _Originally posted by @BanQuanChung

Thanks, i tested with the turbo model and it is very good in terms of accuracy for Vietnamese. But there are 2 problems:
1. It constantly shows similar advertisment lines (Hãy subscribe cho kênh Ghiền Mì Gõ Để không bỏ lỡ những video hấp dẫn). This is an advertisement for a Vietnamese Youtube channel for entertainment videos.
![image](https://github.com/user-attachments/assets/c31530af-20f7-4f26-86df-9b99f24d7783)

(I didn't encounter this kind of ads when testing other models like large-v2 or medium. It seems that the downloaded turbo model has advertisments in it.)

2. I tested 2 sources of turbo models and have different results:

**Source 1:** Download from https://huggingface.co/Purfview/faster-whisper-large-v3-turbo/tree/main and paste into the `_models` folder
Commands: `faster-whisper-xxl.exe %file_list% -pp -o source --batch_recursive --check_files --standard -f srt -m large-v3-turbo --language Vietnamese --device cpu --compute_type float32 --best_of=1 --beam_size 5 --task transcribe --batched`
==> speed: 1.41 audio seconds/s

**Source 2:** Remove the above model and use the following Commands to directly download through the `.bat` file
Commands: `faster-whisper-xxl.exe %file_list% -pp -o source --batch_recursive --check_files --standard -f srt -m turbo --language Vietnamese --device cpu --compute_type float32 --best_of=1 --beam_size 5 --task transcribe --batched --output_dir E:\BQC-TK4\AI-Transcription\Faster-Whisper-XXL_r239.1_windows\Faster-Whisper-XXL\Output --beep_off`
==> speed: 0.35 audio seconds/s

RESULTS: Same accuracy, and still have advertisment lines for both tests.

Please help me out:
1. Remove the advertisments. 
2. Which download source of turbo model is official? (Of course, I prefer the one with faster speed result but not sure if the source is up-to-date or not).

Many thanks, for your great contribution to getting this whisper easy to reach for non-coders.

**Comment by Purfview** [comment]
>Remove the advertisements.

These are hallucinations, all models can produce such.

To reduce probability of hallucinations:
1) Don't use batched mode.
2) Use more accurate VAD: `--vad_method pyannote_v3` (it's slower)
3) Try `-hst 2` (doesn't work in batched mode and it's slower)


>I tested 2 sources of turbo models... -m large-v3-turbo... -m turbo...

`turbo` is a short name of the same official model as `large-v3-turbo`, there is no different turbo models.

**Comment by BanQuanChung** [comment]
I tested 
```
Don't use batched mode.
Use more accurate VAD: --vad_method pyannote_v3 (it's slower)
Try -hst 2 (doesn't work in batched mode and it's slower)
```
With -hst 2, the bat file turned out to be idle. I remove -hst 2 and the result has fewer hallucinations.

However, I tested this commands, and only 1 line of hallucination occur at the end.
`faster-whisper-xxl.exe %file_list% -pp --batch_recursive --check_files --standard -f srt -m turbo --language Vietnamese --device cpu --compute_type float32 --beam_size 5 --task transcribe --batched --output_dir E:\BQC-TK4\AI-Transcription\Faster-Whisper-XXL_r239.1_windows\Faster-Whisper-XXL\Output`

The accuracy is fantastic. Please show me how to remove completely the hallucination. 
Many thanks.

**Comment by BanQuanChung** [comment]
> I tested
> 
> ```
> Don't use batched mode.
> Use more accurate VAD: --vad_method pyannote_v3 (it's slower)
> Try -hst 2 (doesn't work in batched mode and it's slower)
> ```
> 
> With -hst 2, the bat file turned out to be idle. I remove -hst 2 and the result has fewer hallucinations.
> 
> However, I tested this commands, and only 1 line of hallucination occur at the end. `faster-whisper-xxl.exe %file_list% -pp --batch_recursive --check_files --standard -f srt -m turbo --language Vietnamese --device cpu --compute_type float32 --beam_size 5 --task transcribe --batched --output_dir E:\BQC-TK4\AI-Transcription\Faster-Whisper-XXL_r239.1_windows\Faster-Whisper-XXL\Output` Speed: 1.37 audio sec/s (VERY GOOD) The accuracy is fantastic.
> 
> show me how to remove completely the hallucination. Many thanks.

The above arugments did have some more hallucinations as I checked closely.
And I tested these arguments (without batch):
`faster-whisper-xxl.exe %file_list% -pp --check_files --standard -f srt -m turbo --language Vietnamese --device cpu --task transcribe --compute_type float32 --best_of=1 --beam_size 5  --output_dir E:\BQC-TK4\AI-Transcription\Faster-Whisper-XXL_r239.1_windows\Faster-Whisper-XXL\Output --vad_method pyannote_v3 --vad_device cpu`
==> NO HALLUCINATION, EXCELLENT ACCURACY. And speed around 0.8 audio sec/s.
_I am using cpu (XEON E-1505M v6) since .bat file has error running when I use gpu (Display 1: HD p630 and Display 2: NVIDIA Quadro M1200) on this laptop._ 

Any recommendations for better speed with the same accuracy and no hallucination? I am not likely to upgrade my hardware in the far future.
Many thanks, Purf!

**Comment by Purfview** [comment]
>With -hst 2, the bat file turned out to be idle. 

It's working, not "idle".

>I remove -hst 2 and the result has fewer hallucinations.

Fever vs "idle"!? 😁

>However, I tested this commands, and only 1 line of hallucination occur at the end.
>The accuracy is fantastic.

You just removed --best_of=1  from a command...

>The above arugments did have some more hallucinations as I checked closely.
>And I tested these arguments (without batch):
>==> NO HALLUCINATION, EXCELLENT ACCURACY. 

Of course, when you did  "1" & "2" as I wrote you. Now try "-hst 2", it can be slow when fixing your hallucination.
Remove "--best_of=1" for better results.

**Comment by Purfview** [comment]
Btw, try `--compute_type int8_float32`, it will use twice less RAM than float32.
