### ISSUE TITLE
ProxyError SSLError SSLEOFError: EOF occurred in violation of protocol

### ISSUE THREAD

**Issue by cq535454518** [Purfview/whisper-standalone-win#59]
![image](https://github.com/Purfview/whisper-standalone-win/assets/47836815/14335dbb-3d63-42ca-85da-96f61687f38d)
Our region requires vpn to access the extranet, which prevents the software from accessing huggingface properly. can you add options to support proxies?

**Comment by Purfview** [comment]
Check if model download works with this: https://we.tl/t-VLjVUadXXh

**Comment by fireattack** [comment]
Tried with newest [Whisper-Faster_r149.1.zip](https://github.com/Purfview/whisper-standalone-win/releases/download/faster-whisper/Whisper-Faster_r149.1.zip) and this is still broken.

I don't know what versions do you use when package the exe, but this is cause by bug in std lib urllib and is fixed in Python 3.9.13, 3.10.5 and in 3.11.0, respectively. If you can kindly update the embedded python into such version it would be helpful.

**Comment by Purfview** [comment]
> is still broken.

Because nothing was done to fix it and the issue was closed because OP wasn't interested in solving it.

> bug in std lib urllib.

But error comes from `huggingface_hub` and it's using `urllib3`.

Anyway, if I understand [this article](https://ywang-wnlo.github.io/posts/76f6af57.html) correctly the error probably comes from a wrong user's proxy configuration.

**Comment by Purfview** [comment]
What is you proxy configuration?

Here are examples from that article:

```
# Wrong configuration method 
HTTP_PROXY =http:// 127.0.0.1:7890 
HTTPS_PROXY =https:// 127.0.0.1:7890
```

```
# Correct configuration method 
HTTP_PROXY =http:// 127.0.0.1:7890 
HTTPS_PROXY =http:// 127.0.0.1:7890
```

```
# Correct configuration method 
HTTP_PROXY =socks5:// 127.0.0.1:7890 
HTTPS_PROXY =socks5:// 127.0.0.1:7890
```

**Comment by fireattack** [comment]
https://github.com/python/cpython/issues/86793 already has all the details but I will give a quick summary.

The bug is caused by python infers the configurations from registry wrong, not the configurations are wrong itself.

Windows users typically set system-level proxies via Internet Options, not by setting environment variables. In Internet Options, the user typically only set the proxy without any proctol attached (so it should be assumed HTTP), like so:

![image](https://github.com/Purfview/whisper-standalone-win/assets/4130991/d23562f7-5378-4824-ac9f-bac28c472910)

This value is saved in registry `HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ProxyServer` as a singular value of `127.0.0.1:7890`.

Python's urllib, by default, will try to translate this registry to a proxy setting and enable it by default.

However, it translates it wrong (until fixed) to 
```
HTTP_PROXY=http://127.0.0.1:7890 
HTTPS_PROXY=https://127.0.0.1:7890
```

instead of
```
HTTP_PROXY=http://127.0.0.1:7890 
HTTPS_PROXY=http://127.0.0.1:7890
```

huggingface_hub` uses `urllib3` which ultimately uses `urllib` for reading proxy configurations from system, and therefore inherits this bug. 

You can see the ticket there (https://github.com/urllib3/urllib3/issues/2164) which is said "Fixed by https://github.com/python/cpython/pull/26307".

Strictly speaking, this is not a bug of https://github.com/guillaumekln/faster-whisper because at this point, it only depends in the Python version. If you use 3.10.5 or above, it works. If not, it's broken.

**Comment by Purfview** [comment]
Oh, OK.

Python 3.9 doesn't support Windows 7 [I think there is some hack], better I'll try to downgrade urlib3 then.

**Comment by fireattack** [comment]
Yeah, if we use 3.8 that probably is the easiest. 

Alternatively, we can patch https://github.com/python/cpython/blob/3.8/Lib/urllib/request.py manually by replacing 

```
                if '=' in proxyServer:
                    # Per-protocol settings
                    for p in proxyServer.split(';'):
                        protocol, address = p.split('=', 1)
                        # See if address has a type:// prefix
                        if not re.match('(?:[^/:]+)://', address):
                            address = '%s://%s' % (protocol, address)
                        proxies[protocol] = address
                else:
                    # Use one setting for all protocols
                    if proxyServer[:5] == 'http:':
                        proxies['http'] = proxyServer
                    else:
                        proxies['http'] = 'http://%s' % proxyServer
                        proxies['https'] = 'https://%s' % proxyServer
                        proxies['ftp'] = 'ftp://%s' % proxyServer
```


to

```
                if '=' not in proxyServer and ';' not in proxyServer:
                    # Use one setting for all protocols.
                    proxyServer = 'http={0};https={0};ftp={0}'.format(proxyServer)
                for p in proxyServer.split(';'):
                    protocol, address = p.split('=', 1)
                    # See if address has a type:// prefix
                    if not re.match('(?:[^/:]+)://', address):
                        # Add type:// prefix to address without specifying type
                        if protocol in ('http', 'https', 'ftp'):
                            # The default proxy type of Windows is HTTP
                            address = 'http://' + address
                        elif protocol == 'socks':
                            address = 'socks://' + address
                    proxies[protocol] = address
                # Use SOCKS proxy for HTTP(S) protocols
                if proxies.get('socks'):
                    # The default SOCKS proxy type of Windows is SOCKS4
                    address = re.sub(r'^socks://', 'socks4://', proxies['socks'])
                    proxies['http'] = proxies.get('http') or address
                    proxies['https'] = proxies.get('https') or address
```

(Copied from https://github.com/python/cpython/pull/26307/files)

**Comment by Purfview** [comment]
I went with patching urllib, check r153 if it works.

**Comment by fireattack** [comment]
It works, thanks!
